name: Jest Coverage Report

on:
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - uses: actions/checkout@v3
        
      - name: Install Dependencies
        run: npm install jest --save-dev

      - name: Run Jest tests
        run: npm test -- testPathPattern=server